[43기 강혁주] 카트 관리
wecode-bootcamp-korea/43-1st-200ok-backend pull request #6
Opened 2023-03-14 11:07 UTC by rkdgurwn14

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [V] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 상세페이지에서 카트로 상품들이 넘어오도록 호출 및 출력 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 상품 정보를 프런트에서 보내주면 그에 맞는 데이터들을 db에 저장

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항
- feature/mainpage에 대한 내용을 feedback 하기 위해 임시로 push해놓은 것입니다!

2023-03-15 02:14 UTC, Kang-kyunghun requested changes

2023-03-15 02:14 UTC, Kang-kyunghun commented on api/routes/cartRouter.js
> +router.get("", cartController.postCart);
장바구니는 보통 로그인 한 user만 등록 할 수 있어야 합니다. 해당 router에 token을 확인하여 user 정보를 가져올 수 있는 middleware를 추가해 주세요.

2023-03-15 02:14 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +  }
if-else보다는 아래와 같이 객체를 만들어서 사용하는 것이 훨씬 좋을 것 같습니다.
size도 다음과 같이 수정해 주세요.
```suggestion
const colors =  {
  blue: 1,
  black: 2,
  gray: 3,
  red: 4,
  yellow: 5,
  green: 6,
  purple: 7
}
```

2023-03-15 02:14 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +    [quantity]
현재 수량만 넣고 있는데, 확인해 주세요.

2023-03-15 02:14 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +// enum 객체로 정리 object.freeze
위에 if-else를 객체로 바꾸라고 한 review에 enum 객체로 정의까지 적용해 보면 좋겠네요!

2023-03-16 09:18 UTC, Jon9Beom commented
고생하셨습니다 추후에 리팩토링해주세요! 🚀

2023-03-16 09:19 UTC, merged